# Generated by Django 4.2.5 on 2024-02-06 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0108_remove_calculatedvariable_period_and_more"),
        ("webservice", "0020_auto_20220105_1000"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webservicedevice",
            name="web_service_handler",
        ),
        migrations.AddField(
            model_name="webservicedevice",
            name="headers",
            field=models.CharField(
                blank=True,
                help_text="For exemple: {'Authorization': 'TOKEN', 'Content-Type': 'application/json',}",
                max_length=400,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webservicedevice",
            name="payload",
            field=models.CharField(
                blank=True,
                help_text="For exemple: {'type': 'consumption_load_curve', 'usage_point_id': 'ID',}",
                max_length=400,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webservicedevice",
            name="webservice_RW",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Read"), (1, "Write")], default=0
            ),
        ),
        migrations.AddField(
            model_name="webservicedevice",
            name="webservice_content_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Auto"), (1, "XML"), (2, "JSON")], default=0
            ),
        ),
        migrations.AddField(
            model_name="webservicedevice",
            name="webservice_mode",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Path"), (1, "GET"), (2, "POST")], default=0
            ),
        ),
        migrations.AddField(
            model_name="webservicedevice",
            name="write_trigger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ws_write_trigger",
                to="pyscada.variable",
            ),
        ),
        migrations.AlterField(
            model_name="webserviceaction",
            name="write_trigger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ws_write_triggerAction",
                to="pyscada.variable",
            ),
        ),
    ]
