# Generated by Django 4.2.8 on 2024-02-09 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0022_move_action_to_device"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webservicedevice",
            name="webservice_RW",
        ),
        migrations.RemoveField(
            model_name="webservicedevice",
            name="write_trigger",
        ),
    ]
