# Generated by Django 4.2.8 on 2024-02-09 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0023_remove_webservicedevice_webservice_rw_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebServiceAction",
        ),
    ]
