# Generated by Django 5.0.3 on 2024-11-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0024_delete_webserviceaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webservicedevice",
            name="webservice_content_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Auto"), (1, "text/xml"), (2, "application/json")],
                default=0,
            ),
        ),
    ]
